#!/bin/sh
# echo "Installing the latest stable via official script"
# NONINTERACTIVE=1
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# brew install go cmake gcc